/**
 * Dictionnaire de mots FRANÇAIS de EXACTEMENT 7 lettres, en majuscules ASCII
 * (ni accent, ni tiret, ni apostrophe) — contrainte d'affichage dans les cases
 * de l'étoile. Volontairement large : le générateur y cherche par backtracking
 * une configuration qui satisfait les 6 intersections, il lui faut du choix.
 */
export const WORDS7: readonly string[] = [
  'ABEILLE', 'ABRICOT', 'ABSENCE', 'ADRESSE', 'AFFAIRE', 'AFFICHE', 'ALIMENT', 'ALLUMER',
  'AMPLEUR', 'AMUSANT', 'ANGLAIS', 'ANIMAUX', 'ANNONCE', 'ANTENNE', 'APPELER', 'APPUYER',
  'ARDOISE', 'ARMOIRE', 'ARRIVER', 'ARTICLE', 'ARTISTE', 'ASPIRER', 'ASSURER', 'ATELIER',
  'ATTACHE', 'ATTAQUE', 'ATTEINT', 'ATTIRER', 'ATTRAIT', 'AUBERGE', 'AUTOMNE', 'AVERTIR',
  'BAIGNER', 'BAISSER', 'BALANCE', 'BALAYER', 'BANDAGE', 'BANDEAU', 'BANQUET', 'BARRAGE',
  'BARREAU', 'BATTANT', 'BATTEUR', 'BERCEAU', 'BISCUIT', 'BLANCHE', 'BLESSER', 'BLOQUER',
  'BOISSON', 'BONHEUR', 'BORDURE', 'BOUCHER', 'BOUCLER', 'BOUQUET', 'BRANCHE', 'BRIGADE',
  'BRILLER', 'BRISURE', 'BRONZER', 'BUISSON', 'CABARET', 'CABINET', 'CALMANT', 'CAMPING',
  'CANTINE', 'CAPITAL', 'CAPTURE', 'CARESSE', 'CAROTTE', 'CARREAU', 'CASERNE', 'CAUTION',
  'CAVERNE', 'CENSURE', 'CENTRAL', 'CERTAIN', 'CERVEAU', 'CHAGRIN', 'CHALEUR', 'CHAMBRE',
  'CHAMEAU', 'CHANSON', 'CHANTER', 'CHAPEAU', 'CHARADE', 'CHARGER', 'CHARIOT', 'CHASSER',
  'CHEVAUX', 'CHIFFON', 'CHIFFRE', 'CHINOIS', 'CHOISIR', 'CHORALE', 'CIRCUIT', 'CLASSER',
  'CLAVIER', 'CLOCHER', 'COIFFER', 'COLLIER', 'COLLINE', 'COLOMBE', 'COLONNE', 'COLORER',
  'COMBIEN', 'COMBINE', 'COMBLER', 'COMMENT', 'COMMUNE', 'COMPLET', 'COMPLOT', 'COMPOTE',
  'COMPRIS', 'COMPTER', 'CONCERT', 'CONDUIT', 'CONFIER', 'CONFORT', 'CONSEIL', 'CONSOLE',
  'CONTACT', 'CONTENU', 'CONTOUR', 'CORBEAU', 'CORRECT', 'COSTUME', 'COUCHER', 'COULANT',
  'COULEUR', 'COULOIR', 'COURAGE', 'COURANT', 'COURBER', 'COUREUR', 'COUTEAU', 'COUTUME',
  'COUTURE', 'COUVRIR', 'CRAINTE', 'CRAVATE', 'CRISTAL', 'CROISER', 'CUISINE', 'CULOTTE',
  'CULTURE', 'DANSANT', 'DANSEUR', 'DEMANDE', 'DENTIER', 'DERNIER', 'DESSERT', 'DEVENIR',
  'DEVINER', 'DIAMANT', 'DICTION', 'DIRIGER', 'DIVISER', 'DOCTEUR', 'DOMAINE', 'DOSSIER',
  'DOUBLER', 'DOUCEUR', 'DOULEUR', 'DRAPEAU', 'DRESSER', 'DURABLE', 'EFFACER', 'ENDORMI',
  'ENDROIT', 'ENFANCE', 'ENTRAIN', 'ENVOYER', 'ESSAYER', 'ESSENCE', 'EXCITER', 'EXTERNE',
  'EXTRAIT', 'FACTEUR', 'FACTION', 'FACTURE', 'FAMILLE', 'FANFARE', 'FATIGUE', 'FERMENT',
  'FERMIER', 'FERMOIR', 'FICELLE', 'FICHIER', 'FICTION', 'FIGUIER', 'FIGURER', 'FILTRER',
  'FINANCE', 'FISSURE', 'FLAMBER', 'FLEURIR', 'FLOTTER', 'FONDANT', 'FORMULE', 'FORTUNE',
  'FRAGILE', 'FRAPPER', 'FREINER', 'FRISSON', 'FRITURE', 'FROMAGE', 'FRONTAL', 'FROTTER',
  'GAGNANT', 'GALERIE', 'GALETTE', 'GARDIEN', 'GAZELLE', 'GESTION', 'GLISSER', 'GONFLER',
  'GOUFFRE', 'GRAISSE', 'GRANDIR', 'GRATTER', 'GRATUIT', 'GRAVURE', 'GRENADE', 'GRENIER',
  'GRILLER', 'GRIMACE', 'GRIMPER', 'GRONDER', 'GUITARE', 'HABITER', 'HARICOT', 'HAUTEUR',
  'HEUREUX', 'HONNEUR', 'HORLOGE', 'IMMENSE', 'INCLURE', 'INSTANT', 'INSULTE', 'INTERNE',
  'INVITER', 'ITALIEN', 'JANVIER', 'JOINDRE', 'JONGLER', 'JOURNAL', 'JOYEUSE', 'JUMELLE',
  'JUSTICE', 'LAISSER', 'LAITIER', 'LANCEUR', 'LANGAGE', 'LARGEUR', 'LECTEUR', 'LECTURE',
  'LENTEUR', 'LIGOTER', 'LIMITER', 'LOGIQUE', 'LOUCHER', 'LUNETTE', 'MACHINE', 'MAGASIN',
  'MAGIQUE', 'MALHEUR', 'MANETTE', 'MANQUER', 'MANTEAU', 'MARCHER', 'MARIAGE', 'MARMITE',
  'MARQUER', 'MARTEAU', 'MASSIVE', 'MATELAS', 'MENACER', 'MENTEUR', 'MENTION', 'MESSAGE',
  'MESURER', 'METTEUR', 'MINCEUR', 'MIRACLE', 'MISSION', 'MODELER', 'MODERNE', 'MOISSON',
  'MONNAIE', 'MONTAGE', 'MONTANT', 'MONTEUR', 'MONTRER', 'MONTURE', 'MORCEAU', 'MORDANT',
  'MORSURE', 'MOUETTE', 'MOURANT', 'MURMURE', 'MUSICAL', 'MUSIQUE', 'NACELLE', 'NATUREL',
  'NERVEUX', 'NOURRIR', 'NOUVEAU', 'NUAGEUX', 'OBTENIR', 'OCCUPER', 'OMBRAGE', 'OPPOSER',
  'ORIGINE', 'OUBLIER', 'OUVRAGE', 'OUVRIER', 'PALETTE', 'PALMIER', 'PANIQUE', 'PANNEAU',
  'PARADIS', 'PARFAIT', 'PARJURE', 'PARTAGE', 'PARTANT', 'PASSAGE', 'PASSANT', 'PASSION',
  'PATIENT', 'PAYSAGE', 'PEIGNER', 'PEINTRE', 'PENCHER', 'PENDANT', 'PENSEUR', 'PERCHER',
  'PERDANT', 'PINCEAU', 'PIQUANT', 'PLACARD', 'PLAFOND', 'PLAINTE', 'PLAISIR', 'PLANCHE',
  'PLANEUR', 'PLANTER', 'PLATEAU', 'PLATINE', 'PLONGER', 'PLUMAGE', 'POIGNET', 'POINTER',
  'POIREAU', 'POISSON', 'POMMIER', 'POMPIER', 'PORTAIL', 'PORTANT', 'PORTEUR', 'PORTION',
  'POSTURE', 'POULAIN', 'POUSSER', 'POUVOIR', 'PREMIER', 'PRENDRE', 'PRESSER', 'PRODUIT',
  'PROFOND', 'PRUDENT', 'PRUNIER', 'PUBLIER', 'QUITTER', 'RANCUNE', 'RAPPORT', 'RECETTE',
  'REMPLIR', 'RENTRER', 'RESSORT', 'RESTANT', 'RETENIR', 'REVENIR', 'RIGOLER', 'ROMANCE',
  'RONFLER', 'RONGEUR', 'ROULANT', 'ROULEAU', 'RUPTURE', 'SABLIER', 'SANDALE', 'SANGLOT',
  'SARDINE', 'SAUVAGE', 'SAUVEUR', 'SAVANTE', 'SCIENCE', 'SECONDE', 'SECTEUR', 'SEMAINE',
  'SEMELLE', 'SENTEUR', 'SENTIER', 'SERMENT', 'SERPENT', 'SERRURE', 'SERVANT', 'SERVEUR',
  'SESSION', 'SIFFLER', 'SIFFLET', 'SILENCE', 'SOIGNER', 'SOMBRER', 'SOMMEIL', 'SONDAGE',
  'SORTANT', 'SOUFFLE', 'SOULIER', 'SOURCIL', 'SOURIRE', 'SOUTIEN', 'SOUVENT', 'SPIRALE',
  'SPORTIF', 'STATION', 'SUCRIER', 'SUIVANT', 'SUPPORT', 'SURFACE', 'SURSAUT', 'TABLEAU',
  'TABLIER', 'TAILLER', 'TAMBOUR', 'TARTINE', 'TAUREAU', 'TAVERNE', 'TERRAIN', 'TERRINE',
  'TEXTURE', 'TOITURE', 'TORRENT', 'TOUCHER', 'TOURNER', 'TRANCHE', 'TRAVAIL', 'TRIBUNE',
  'TRICHER', 'TROMPER', 'TROTTER', 'TROUBLE', 'TROUVER', 'URGENCE', 'USINAGE', 'VACANCE',
  'VAINCRE', 'VANILLE', 'VANTARD', 'VECTEUR', 'VEDETTE', 'VEILLER', 'VENDEUR', 'VERDURE',
  'VERGLAS', 'VERSANT', 'VERSION', 'VIBRANT', 'VILLAGE', 'VIOLENT', 'VISITER', 'VITESSE',
  'VITRAIL', 'VITRINE', 'VOILIER', 'VOILURE', 'VOISINE', 'VOITURE', 'VOYAGER', 'VOYELLE',
];

/**
 * Index (position, lettre) → mots. Construit une seule fois au chargement :
 * c'est lui qui rend la recherche de solution quasi instantanée (le générateur
 * n'énumère jamais le dictionnaire entier, il intersecte deux listes indexées).
 */
export const WORDS_BY_POS_LETTER: ReadonlyArray<ReadonlyMap<string, readonly string[]>> = (() => {
  const idx: Map<string, string[]>[] = Array.from({ length: 7 }, () => new Map<string, string[]>());
  for (const word of WORDS7) {
    for (let p = 0; p < 7; p++) {
      const letter = word[p];
      const bucket = idx[p].get(letter);
      if (bucket) bucket.push(word);
      else idx[p].set(letter, [word]);
    }
  }
  return idx;
})();

/** Mots portant `letter` à la position `pos` (liste vide si aucun). */
export function wordsWithLetterAt(pos: number, letter: string): readonly string[] {
  return WORDS_BY_POS_LETTER[pos].get(letter) ?? [];
}
